- name: Update exim
  portage:
    newuse: yes
    update: yes
    package: mail-mta/exim
  notify: Restart exim

- name: Update debian exim.conf
  command: '/usr/sbin/update-exim4.conf'
  notify: Restart exim
  listen: Assemble final configuration
  when: "ansible_os_family == 'Debian' or ansible_os_family == 'Devuan'"

- name: Restart exim
  service:
    name: "{{ exim_service }}"
    state: restarted
